#include "css.h"
const char *css_ua_sheet =
"html,address,blockquote,body,dd,div,dl,dt,fieldset,form,frame,frameset,h1,h2,h3,h4,h5,h6,noframes,ol,p,ul,center,dir,hr,menu,pre,"
"article,aside,footer,header,hgroup,main,nav,section,figure,figcaption,details,summary,legend,search,dialog,optgroup{display:block}"
"head,script,style,link,meta,title,base,template,noscript,datalist,param,area,[hidden]:not([hidden=until-found]),source,track,dialog:not([open]){display:none}"
"li{display:list-item}table{display:table;border-collapse:separate;border-spacing:2px;box-sizing:border-box;text-indent:0}"
"thead{display:table-header-group;vertical-align:middle}tbody{display:table-row-group;vertical-align:middle}tfoot{display:table-footer-group;vertical-align:middle}"
"tr{display:table-row;vertical-align:inherit}td,th{display:table-cell;vertical-align:inherit;padding:1px}th{font-weight:bold;text-align:-internal-center}"
"caption{display:table-caption;text-align:center}col{display:table-column}colgroup{display:table-column-group}"
"body{margin:8px}p,dl,blockquote,figure,pre,xmp,plaintext,listing{margin:1em 0}blockquote,figure{margin-left:40px;margin-right:40px}"
"h1{font-size:2em;margin:.67em 0;font-weight:bold}h2{font-size:1.5em;margin:.83em 0;font-weight:bold}h3{font-size:1.17em;margin:1em 0;font-weight:bold}"
"h4{margin:1.33em 0;font-weight:bold}h5{font-size:.83em;margin:1.67em 0;font-weight:bold}h6{font-size:.67em;margin:2.33em 0;font-weight:bold}"
"ul,menu,dir{list-style-type:disc;margin:1em 0;padding-left:40px}ol{list-style-type:decimal;margin:1em 0;padding-left:40px}"
"ul ul,ol ul,ul ol,ol ol{margin-top:0;margin-bottom:0}ul ul,ol ul{list-style-type:circle}dd{margin-left:40px}"
"b,strong{font-weight:bold}i,em,cite,var,dfn,address{font-style:italic}u,ins{text-decoration:underline}s,strike,del{text-decoration:line-through}"
"pre,code,kbd,samp,tt,xmp,plaintext,listing{font-family:monospace}pre,xmp,plaintext,listing{white-space:pre}code,kbd,samp,tt{font-size:.8125em}"
"small{font-size:smaller}big{font-size:larger}sub{vertical-align:sub;font-size:smaller}sup{vertical-align:super;font-size:smaller}"
"a:any-link{color:#0000ee;text-decoration:underline;cursor:pointer}mark{background-color:yellow;color:black}"
"hr{border:1px inset #eee;margin:.5em auto;color:gray;overflow:hidden}center{text-align:center}nobr{white-space:nowrap}"
"img,video,canvas,iframe,embed,object,svg{display:inline-block}iframe{border:2px inset #eee;width:300px;height:150px}video{width:300px;height:150px;object-fit:contain}"
"svg:not(:root){overflow:hidden}audio:not([controls]){display:none}audio{width:300px;height:54px;display:inline-block}"
"input,select,button,textarea{display:inline-block;font-size:13.333px;font-family:system-ui;margin:0;color:black}"
"input{padding:1px 2px;border:2px inset #767676;background:white;width:150px;height:auto;line-height:normal}input[type=hidden]{display:none}"
"input[type=checkbox],input[type=radio]{width:13px;height:13px;margin:3px;padding:0;border:1px solid #767676}"
"input[type=submit],input[type=button],input[type=reset],button{padding:1px 6px;border:2px outset #767676;background-color:#efefef;text-align:center;width:auto;cursor:default}"
"select{border:1px solid #767676;background:white;padding:1px}textarea{border:1px solid #767676;padding:2px;white-space:pre-wrap;width:180px;height:32px;font-family:monospace}"
"option{display:block;white-space:nowrap}select option{display:none}fieldset{margin:0 2px;padding:.35em .75em .625em;border:2px groove #c0c0c0}"
"legend{padding:0 2px}summary{display:list-item}details:not([open])>:not(summary){display:none}"
"ruby{display:ruby}rt{font-size:50%}q::before{content:open-quote}q::after{content:close-quote}"
"slot{display:contents}dialog[open]{position:absolute;left:0;right:0;margin:auto;border:solid;padding:1em;background:white;color:black;width:fit-content}"
"[popover]:not(:popover-open){display:none}marquee{display:inline-block}"
;
